[package]
name = "basic_usage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.20", features = ["default", "time", "rt", "rt-multi-thread", "sync", "macros"] }
serde_json = "1.0"

core = { path = "../../core" }

[dependencies.libp2p]
version = "0.44"
features = [
	"identify",
	"kad",
	"mplex",
	"noise",
	"ping",
	"serde",
	"tcp-tokio",
]

[workspace]