[network]
p2pport = 40000
addr = "/ip4/127.0.0.1/tcp"
accesspoints = []

[node]
httpport = 3000
httpaddr = "127.0.0.1"
key-derivator = "Ed25519"
digest-derivator = "Blake3_256"
replication-factor = 0.25
timeout = 3000

# [database]
# path = "./store"

[governance]
members = []